"""Shared defaults for printable Lucas-square output."""

DEFAULT_PAGE_WIDTH = 12.0
DEFAULT_PAGE_HEIGHT = 9.0
DEFAULT_SVG_UNITS_PER_INCH = 100
DEFAULT_MARGIN = 0.45
TARGET_RATIO = DEFAULT_PAGE_WIDTH / DEFAULT_PAGE_HEIGHT
DEFAULT_MAX_ITERATIONS = 70
